name: Test Docker Password

on:
  workflow_dispatch:

jobs:
  test-login:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login Test
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Check if secret is empty
        run: |
          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "DOCKER_PASSWORD is EMPTY!"
            exit 1
          else
            echo "DOCKER_PASSWORD is set."
          fi